name: Colorful
version: 0.1.0
main: io.github.jesecci.Main
api-version: 1.18
author: jesecci
description: wild expanding plugin
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.6.10
  - io.github.monun:kommand:2.8.0
commands:
